version: 2.1

orbs:
  php: circleci/php@1.1
  wp-svn: studiopress/wp-svn@0.2

jobs:
  lint-test:
    parameters:
      php-version:
        type: string
    docker:
      - image: cimg/php:<< parameters.php-version >>
    steps:
      - checkout
      - run:
          name: Testing and linting
          command: |
            composer update
            composer test
            composer lint
  svn-deploy:
    docker:
      - image: cimg/php:8.3
    steps:
      - checkout
      - run:
          name: "Building"
          command: composer install -o --no-dev
      - wp-svn/deploy-plugin:
          wporg-assets-directory: wporg

workflows:
  version: 2
  test-deploy:
    jobs:
      - lint-test:
          filters:
            tags:
              only: /.*/
          matrix:
            parameters:
              php-version: [ '8.0', '8.2', '8.5' ]
      - svn-deploy:
          requires:
            - lint-test
          filters:
            tags:
              only: /^\d+\.\d+\.\d+$/
            branches:
              ignore: /.*/
      - approval-for-deploy-tested-up-to-bump:
          type: approval
          requires:
            - lint-test
          filters:
            tags:
              ignore: /.*/
            branches:
              only: /^bump-tested-up-to.*/
      - wp-svn/deploy-tested-up-to-bump:
          requires:
            - approval-for-deploy-tested-up-to-bump
